apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-network
  labels:
    app: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-network
  template:
    metadata:
      labels:
        app: social-network
    spec:
      containers:
        - name: social-network
          image: ghcr.io/olegmedvedev/social-network:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20 