apiVersion: v1
kind: Service
metadata:
  name: social-network
  labels:
    app: social-network
spec:
  type: NodePort
  selector:
    app: social-network
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 