// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friend struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type FriendRequest struct {
	ID        string `json:"id"`
	From      *User  `json:"from"`
	To        *User  `json:"to"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
